[tool.poetry]
name = "halfspace-optimizer"
version = "0.1.2"
description = "Cutting-plane solver for mixed-integer convex optimization problems"
license ="MIT"
authors = [
    "Joshua Ivanhoe <joshua.k.ivanhoe@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/joshivanhoe/halfspace"
documentation = "https://joshivanhoe.github.io/halfspace/"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [
    { include = "halfspace", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
mip = ">=1.15.0"
numpy = ">=1.25.2"
pandas = ">=2.0.3"

[tool.poetry.group.dev.dependencies]
mypy = "*"
pre-commit = "*"
ruff = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["D"]  # pydocstyle

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]  # Ignore all directories named `tests` for pydocstyle

[tool.mypy]
ignore_missing_imports = true
exclude = ["convex_term.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
